### ISSUE TITLE
Problems with files larger than 10mb

### ISSUE THREAD

**Issue by mlegenhausen** [MobileChromeApps/zip#38]
I have a problem with files bigger than 10mb which can lead to a memory warnings till a signal 9 which kills the complete app. Is there any maximum you know?

**Comment by mlegenhausen** [comment]
Solved by my own pull request.

**Comment by mmocny** [comment]
Which PR?  I can't find your fork.  Do you mean this patch: https://github.com/MobileChromeApps/zip/commit/ce58b41deaf01132eea99246aca267222c9b5af6

**Comment by mmocny** [comment]
Seems thats what you meant, in which case, thanks for checking back in!

**Comment by mlegenhausen** [comment]
I hate open issues, so do maybe others ;)
